### ISSUE TITLE
How to access to express?

### ISSUE THREAD

**Issue by timaschew** [pilwon/ultimate-seed#109]
I don't see that express is required.  
I searched in this file: https://github.com/pilwon/ultimate-seed/blob/master/server/app.js but didn't find where the property `express` of the object `app.servers` is set.

**Comment by pilwon** [comment]
@timaschew `ultimate` is the dependency library for `ultimate-seed`. [This is what you are looking for.](https://github.com/pilwon/node-ultimate/search?q=express)

**Comment by timaschew** [comment]
thanks ;)
