### ISSUE TITLE
Passport redirect for Facebook is always to localhost

### ISSUE THREAD

**Issue by ghost** [pilwon/ultimate-seed#20]
For the life of me I can't figure out why the redirect url is always Facebook for my Heroku app. When I try to login with Facebook, I get an error, but the essence of it is that the redirect callback is always set to localhost instead of my domain. Am I missing a piece of configuration to get it to use the domain instead?

https://www.facebook.com/dialog/oauth?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Ffacebook%2Fcallback&scope=email&client_id=152247794979222&type=web_server

**Comment by pilwon** [comment]
@dariusriggins The server app launched with an environment variable of `NODE_ENV=heroku` uses `url` variable configurable in `config/heroku.json` for its base URL. It is read in [`ultimate.server.middleware.passport.facebook`](https://github.com/pilwon/node-ultimate/blob/b27fb449c773ae8d115bd5b5ebe71bd9b6dcda0c/lib/server/middleware/passport/facebook.js#L56), then the final callback url that you see in the query string is [built here](https://github.com/pilwon/node-ultimate/blob/b27fb449c773ae8d115bd5b5ebe71bd9b6dcda0c/lib/server/middleware/passport/facebook.js#L33). You either didn't set the environment variable correctly or didn't set the url in heroku configuration file.

**Comment by ghost** [comment]
I was an idiot and just copied my config over the top of the heroku config, not realizing the additional parameter was there. Thanks.
