### ISSUE TITLE
Log out after navigating

### ISSUE THREAD

**Issue by jaulz** [pilwon/ultimate-seed#40]
When I log in and afterwards navigate to either "Express" or an external page (e.g. http://github.com/pilwon/ultimate-seed), the session is lost and I'm logged out. However navigating to "Backbone" or "Account" works as designed :)

**Comment by pilwon** [comment]
@jaulz Thanks for reporting this. I confirmed the problem exists in the current code base. I'll have a look what happened with recent code changes.

**Comment by pilwon** [comment]
@jaulz This bug was caused by commit https://github.com/pilwon/node-ultimate/commit/a12f85573e8f8b7f58706c1ad304c023d3098f93. (`path.join` !== `url.resolve`)

**Comment by pilwon** [comment]
https://github.com/pilwon/node-ultimate/commit/0e79e69925d3726b0f8847e0d8860c88ae43f430
