### ISSUE TITLE
Express static configuration has typo error

### ISSUE THREAD

**Issue by vadiraja** [pilwon/ultimate-seed#44]
I don't if anyone is using this in production mode, but there is a typo in Ultimate module, express.js.

'proudction' should be 'production'

 _server.configure('heroku', 'proudction', function () {

**Comment by pilwon** [comment]
@vadiraja Thanks so much for the catch. I should've caught this typo earlier. In case you're wondering, yes I use ultimate for several production apps.

**Comment by pilwon** [comment]
Fixed here: https://github.com/pilwon/node-ultimate/commit/e147f8080fe827ce256f1badca5f7f6f91143adf
