### ISSUE TITLE
bcrypt Error: Could not load the bindings file.

### ISSUE THREAD

**Issue by remicastaing** [pilwon/ultimate-seed#54]
I'm using:
- node v0.10.21
- npm 1.3.11
- grunt v0.4.1
- grunt-cli v0.1.9
- mongodb 2.4.7

```
Fatal error: Server ["/Users/remi/git/ultimate-seed/server"] -  Error: Could not load the bindings file. Tried:
 → /Users/remi/git/ultimate-seed/node_modules/bcrypt/build/bcrypt_lib.node
 → /Users/remi/git/ultimate-seed/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /Users/remi/git/ultimate-seed/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /Users/remi/git/ultimate-seed/node_modules/bcrypt/out/Debug/bcrypt_lib.node
 → /Users/remi/git/ultimate-seed/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /Users/remi/git/ultimate-seed/node_modules/bcrypt/out/Release/bcrypt_lib.node
 → /Users/remi/git/ultimate-seed/node_modules/bcrypt/Release/bcrypt_lib.node
 → /Users/remi/git/ultimate-seed/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /Users/remi/git/ultimate-seed/node_modules/bcrypt/compiled/0.10.21/darwin/x64/bcrypt_lib.node
```

**Comment by pilwon** [comment]
@remicastaing `npm rebuild` should resolve this issue.

**Comment by remicastaing** [comment]
It did!
Thank's @pilwon.
Now, time for trying out.

**Comment by pilwon** [comment]
@remicastaing Awesome! Let me know how it goes. Feedback appreciated :+1:

**Comment by one-more** [comment]
Got the same error. `npm rebuild` fails.
- node v5.11.0 
- npm  v3.8.7

**Comment by MaximilianLloyd** [comment]
Npm rebuild fails.

**Comment by nirmalrizal** [comment]
same error here.. what to do??

**Comment by esthersweon** [comment]
It could be an issue with bcrypt itself: http://stackoverflow.com/questions/29320201/error-installing-bcrypt-with-npm

`npm install --save bcryptjs && npm uninstall --save bcrypt`

Change all your `require('bcrypt')` statements to `require('bcryptjs')`.

Known bcrypt issue: https://github.com/kelektiv/node.bcrypt.js/issues/432

**Comment by cristianhoyos66-zz** [comment]
Another option could be upgrading meteor version, since 1.3.* works perfectly
