### ISSUE TITLE
How to generate html version of client-build

### ISSUE THREAD

**Issue by steve21124** [pilwon/ultimate-seed#66]
How to generate the html version of client-build? I plan to host client-build as static files and nodejs in the server.

thanks

**Comment by steve21124** [comment]
found the answer using grunt html

**Comment by steve21124** [comment]
sorry, reopen. seems like there are two choice, using Grunt Concat and grunt-html-build. the ultimate-seed already have GruntConcat but not being used in GruntFile yet

**Comment by steve21124** [comment]
possible sample to use grunt-html-build

<pre>
    fixturesPath: '<%= project.path.dist %>',
    htmlbuild: {
        dist: {
            src: 'index.html',
            dest: '<%= project.path.dist %>/',
            options: {
                beautify: true,
                prefix: '//some-cdn',
                relative: true,
                scripts: {
                    bundle: [
                        '<%= fixturesPath %>/scripts/*.js',
                        '!**/main.js',
                    ],
                    main: '<%= fixturesPath %>/scripts/main.js'
                },
                styles: {
                    bundle: [
                        '<%= fixturesPath %>/css/libs.css',
                        '<%= fixturesPath %>/css/dev.css'
                    ],
                    test: '<%= fixturesPath %>/css/inline.css'
                },
                sections: {
                    views: '<%= fixturesPath %>/views/**/*.html',
                    templates: '<%= fixturesPath %>/templates/**/*.html',
                    layout: {
                        header: '<%= fixturesPath %>/layout/header.html',
                        footer: '<%= fixturesPath %>/layout/footer.html'
                    }
                },
                data: {
                    // Data to pass to templates
                    version: "0.1.0",
                    title: "test",
                },
            }
        }
    },
</pre>

**Comment by pilwon** [comment]
You can drop your static files in `static` directory. If there's any reason you need to build using grunt, check out [our old code snapshot](https://github.com/pilwon/ultimate-seed/tree/c3c7e36b8a35ff779ceb4bf2b8745924affa9d11). We used to have `index.html` in `client` directory.
