### ISSUE TITLE
Is there social gem that work well with ultimate-seed?

### ISSUE THREAD

**Issue by steve21124** [pilwon/ultimate-seed#73]
When searching for "social" express gem, I found https://github.com/dai-shi/social-cms-backend. Is there any other social gem that work well with ultimate-seed?

thanks

**Comment by pilwon** [comment]
@steve21124 What you see in the demo gif of `social-cms-backend` is indeed pretty easy to do with `ultimate-seed`. Not sure what you mean by social gem.

**Comment by steve21124** [comment]
thanks. and agree it is pretty easy to do. Social means... users,posts,like,follow,comments,etc.
