### ISSUE TITLE
Running "grunt" from command line, starts up app but with errors (EMFILE, ulimit)

### ISSUE THREAD

**Issue by frankbolviken** [pilwon/ultimate-seed#74]
![skjermbilde 2013-11-30 kl 14 13 15](https://f.cloud.github.com/assets/688190/1648785/35f3096e-59c1-11e3-8896-d43ca71157b3.png)
I run "grunt" in the terminal, and the app launches. But when grunt WATCH is starting to run, it just keeps printing out these messages:

After all this, the app is started and functioning, but live reload and stuff do not work. I have to manually shut down, and execute "grunt" again for every change.

**Comment by pilwon** [comment]
@frankbolviken Could you try increasing the `ulimit` of your system?

**Comment by frankbolviken** [comment]
Adding "limit maxfiles 16384 32768" to /etc/launchd.conf seems to fix the problem. Thanks for the heads up @pilwon But why is it loading that many files at the same time? it's not THAT many files in the app?
Nonetheless, it works :)

**Comment by pilwon** [comment]
@frankbolviken I'm guessing it's some sort of inefficiency in the latest version of `grunt-contrib-watch` because I haven't seen this issue before. Thanks for reporting this, we'll see if we can find some fix without touching `ulimit`.
