### ISSUE TITLE
WebSocket connection ... failed: Unexpected response code: 502 

### ISSUE THREAD

**Issue by LarryEitel** [pilwon/ultimate-seed#78]
Just wrapping my head around socket.io. It is not immediately obvious where to poke around to resolve this error:

`WebSocket connection to 'ws://m.ourfield.org/socket.io/1/websocket/lGrcXjTQkWbeuk9QELbq' failed: Unexpected response code: 502`

Perhaps related, the following is also recurring continuously:

`Uncaught ReferenceError: io is not defined`

Clues are appreciated. :)

**Comment by pilwon** [comment]
@LarryEitel Make sure your web server supports websocket. ([Heroku](https://devcenter.heroku.com/articles/heroku-labs-websockets), [Nginx](http://nginx.com/news/nginx-websockets/), etc...)

**Comment by LarryEitel** [comment]
Thank you @pilwon. For anyone tuning in, here is what my nginx conf looks like now:

``` shell
server {
    listen       80;
    server_name  m.ourfield.org;

    access_log   /var/log/nginx/m.ourfield.org.access.log;
    error_log    /var/log/nginx/m.ourfield.org.error.log;

    location / {
        access_log off;
        proxy_pass http://m.ourfield.org:50001;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # WebSocket support (nginx 1.4)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /socket.io/ {
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

If anyone has any refinements they would like to suggest, do share. :)

**Comment by Satann** [comment]
@LarryEitel,i meet the same case with you, now it works,thank you
