### ISSUE TITLE
/account/summary broken links from connect buttons

### ISSUE THREAD

**Issue by slim2000** [pilwon/ultimate-seed#79]
Hello,

First... AWESOME project, thank you!

The seed works great so far though I'm experiencing one issue.  Once I've done a login with any of the third party services (e.g. Facebook), and then I look at my profile at /account/summary, if I click on the 'other' two services to connect to (e.g. Google or Twitter) then I get a 404 error.   However, if I back out to the index page and click on either of the two remaining services they work fine.

I'll be digging further at some point and will do a pull if I find anything.  Just saw that you guys were in the code today so I thought I'd highlight this issue.

Thanks again for the great work.

**Comment by pilwon** [comment]
@slim2000 I'm glad you like the project and thanks for reporting the error. I'll have a look at this.
