### ISSUE TITLE
What's the reason to use grunt-browserify2 as opposed to grunt-browserify?

### ISSUE THREAD

**Issue by yaru22** [pilwon/ultimate-seed#82]
It looks like [grunt-browserify](https://github.com/jmreidy/grunt-browserify) is more active than [grunt-browserify2](https://github.com/shanejonas/grunt-browserify2). And it seems to support Browserify v3 as well.

Just curious, what was the reason to use grunt-browserify2?

Thanks.

**Comment by pilwon** [comment]
@yaru22 Not sure. Probably at the time I set up it didn't support browserify2. Right now it works fine but I don't mind switching if that's a better way to go.
