### ISSUE TITLE
what's the 'storage/s3' object used for in config?

### ISSUE THREAD

**Issue by 0xgeert** [pilwon/ultimate-seed#86]
What's the 'storage' object used for in the config files? I.e.: 

```
    "storage": {
      "_use": "s3",
      "backend": {
        "cloudFiles": {
          "container": {
            "main": "@@@@@"
          }
        },
        "s3": {
          "bucket": {
            "main": "@@@@@"
          }
        }
      }
     }
```

**Comment by pilwon** [comment]
@gebrits It is currently not used anywhere in the seed. It is more of a guideline or a suggestion. You can safely remove those values in config or just leave it as is. You will find this config object convenient when your application requires integration with a cloud-based storage service.
