### ISSUE TITLE
REPL failure

### ISSUE THREAD

**Issue by theganyo** [pilwon/ultimate-seed#89]
Hey. Was reading about using the REPL here:

https://github.com/pilwon/ultimate-seed#using-repl-read-eval-print-loop

Tried the command:

`nc -U /tmp/ultimate-repl`

But it just silently fails (even when I use -v). Upon investigation, I don't see a config item for this in the `config/*.json` files. Nor does the `/tmp/ultimate-repl` directory exist.

OS X 10.9.1, node v0.10.25

Thoughts? Thanks!
Scott

**Comment by yaru22** [comment]
@scottganyo, could you try changing `server.repl` to `true` in `project.json` file and try again?

**Comment by theganyo** [comment]
Not quite.. but close enough. I figured it out from there.

Once that property is enabled, it started creating the appropriate files in `/tmp`. However, the files created in `/tmp` have the PID as part of the name. So now I can connect to the file with the appropriate PID appended. Ie:

`nc -U /tmp/ultimate-repl.98996`

So there's definitely a doc issue... and maybe also a code issue, but it's working!

Thanks!
Scott
