### ISSUE TITLE
Can't figure out the wiring

### ISSUE THREAD

**Issue by theganyo** [pilwon/ultimate-seed#90]
Hey guys,

This may just be an angular question, but I'm not sure and I haven't found any documentation on how all this stuff wires together... so please forgive a stupid question...

Basically, I'm just trying to figure out how to wire up a new page on the client to a new service on the server using the cool angular and rectangular stuff. I started with something simple in the /server hierarchy:

```
// server/routes.js:
  s.get('/catalog', c.catalog.catalog.index);


// server/controllers/catalog/catalog.js:
function index(req, res) {
  res.render('catalog/index', {
    items: ['one', 'two']
  });
}
exports.index = index;

// server/views/catalog/index.hbs
<div class="container">
  <p>{{items}}</p>
</div>
```

Now I can go to the /catalog url and that shows up. Yay. 

However, what I really want is to leverage the angular and rest stuff to have all the nice MVC with a REST server... but despite watching videos on angular and reading up on the framework nothing I've done seems to work in this project. 

Hopefully I'm just missing something straightforward. Is there documentation or a checklist of how to create, register, and use a service in ultimate-seed?

Thanks,
Scott

**Comment by pilwon** [comment]
@scottganyo Have a look at how `features` is implemented. Angular fetches the `features` data from the features API endpoint from the server.

**Comment by theganyo** [comment]
Yeah, I tried that. Anyway, never mind. I'm switching my strategy to something simpler. Thanks!

**Comment by pilwon** [comment]
@scottganyo `ultimate-seed` is already set up to use MVC (both on server and client sides) and the seed itself contains example code demonstrating different ways to use the seed. I'm not sure what you're having trouble with but this may help you: #58 and #65
