### ISSUE TITLE
Not working with angular-ui-router#0.2.7

### ISSUE THREAD

**Issue by denysbutenko** [pilwon/ultimate-seed#91]
Only empty footer visible on page.

```
Running "browserify2:dev" (browserify2) task
>> Error: module "./bower_components/angular-ui-router/release/angular-ui-router" not found from "/Users/xxx/dev/test/client/js/node_modules/angular.ui.js"
File written to: .tmp/js/main.js
```

After install angular-ui-router#0.2.0 - works fine!

**Comment by pilwon** [comment]
@denysbutenko Can you `git checkout` the latest version and run `bower install` again?

**Comment by denysbutenko** [comment]
@pilwon Yes, this works fine, if I'm installing with method 2, but if install with `yo generator-ultimate` not work.

**Comment by pilwon** [comment]
@denysbutenko Ah right, I forgot to update yeoman package.

**Comment by pilwon** [comment]
@denysbutenko Just updated yeoman package. Please try again now. Thanks for reporting.
