### ISSUE TITLE
Get blank browser window when I start the application

### ISSUE THREAD

**Issue by dibster** [pilwon/ultimate-seed#92]
Tried both yo ultimate-seed and git clone method. Same problem. Have checked and I have the correct version of node. Mongo and redis installed locally.

I have been building a prototype of an app using the angular-seed , and would like to investigate this project as a framework. I haven't changed anything, wanted to start it up and see what it does....

This is what I get when I start the app (using grunt) 

```
  "session": {
    "_use": "redis",
    "key": "sid",
    "secret": "UlTiMaTeSeCrEtKeY",
    "store": {
      "mongo": {
        "collection": "sessions"
      },
      "redis": {
        "prefix": "ultimate-seed:sessions"
      }
    }
  },
  "socketio": {
    "store": "redis"
  },
  "storage": {
    "_use": "s3",
    "backend": {
      "cloudFiles": {
        "container": {
          "main": "@@@@@"
        }
      },
      "s3": {
        "bucket": {
          "main": "@@@@@"
        }
      }
    }
  }
}
to: wrong arguments

debug: [app] app.config.session.store.redis: {
  "prefix": "ultimate-seed:sessions"
}
info: socket.io started

```

**Comment by pilwon** [comment]
@dibster Your `grunt` output looks fine. I've just installed fresh using the current code base and it seems to work fine. I'd like to help with debugging but please provide more info:
- What do you see when you run `node server` after `grunt`?
- What do you see when you do `view source` in your browser?
- What do you have in `.tmp/js/main.js`?

**Comment by dibster** [comment]
```

  }
}
to: wrong arguments

debug: [app] app.config.session.store.redis: {
  "prefix": "ultimate-seed:sessions"
}
info: socket.io started
Web server started on port:3000, no hostname specified [pid: 19261]

Running "open:dev" (open) task

Running "watch" task
Waiting...

```

main.js, will tar and upload somewhere

view source get "No Data Received"

**Comment by dibster** [comment]
main.js 

https://www.wetransfer.com/downloads/ee1c55854aa6477b25160db4d026826220140210104648/1ecd2dfcebe1fe3cc900f29d0fc0694f20140210104648/a1a6bb

**Comment by pilwon** [comment]
@dibster Did you accidentally close this issue? You don't need to show the entire `main.js` file. What operating system do you use?

**Comment by dashenhurst** [comment]
yes I did close it by mistake

I use ubuntu 13.04

**Comment by pilwon** [comment]
@dashenhurst If those files are correctly generated and you don't see anything served by the express server, static file serving middleware of express is probably not working correctly. Do you see the error page at `http://localhost:3000/404.html`?

**Comment by dibster** [comment]
No that doesn't come up either. So looks like it is some sort of express express problem then.

I will have to investigate this later, as this is a side project and I am at work at the moment

**Comment by dashenhurst** [comment]
hello, I rebuilt my ubuntu machine and its now working fine, it is very possible that my express installation got messed up at some stage, and as I have been installing many frameworks and all sorts of things on it , a rebuild was necessary. This post is probably not useful to anyone so probably delete it

I will let you know how it works as i plan to migrate my angular-seed project into your structure

**Comment by pilwon** [comment]
@dashenhurst Glad it's working now. Hope you enjoy this seed.
