### ISSUE TITLE
Heroku needs updating

### ISSUE THREAD

**Issue by bluepeter** [pilwon/ultimate-seed#93]
The Heroku link hasn't been updated for a while. It was confusing when I couldn't find the "status" link in the nav bar on my local version, when it's clearly there in the demo. I saw that that link has been moved, but that took a bit of time to track down.

**Comment by pilwon** [comment]
@bluepeter The latest version 551b36a79188136c6ceb41a8f3b6e8562e025c0c has been deployed at http://ultimate-seed.herokuapp.com
